from kimfunction import*

bob.speed(0)
bob.pensize(2)
turtle.bgcolor("black")

bob.begin_fill()
bob.color("springgreen")
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-120,0)
bob.pendown()
bob.color("khaki")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(60,60)
bob.pendown()
bob.color("mediumblue")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-60,60)
bob.pendown()
bob.color("lightcoral")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-180,60)
bob.pendown()
bob.color("orchid")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(180,60)
bob.pendown()
bob.color("deepskyblue")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(120,0)
bob.pendown()
bob.color("crimson")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(60,-60)
bob.pendown()
bob.color("purple")
bob.begin_fill()
bob.circle(50)
bob.end_fill()


bob.penup()
bob.goto(-60,-60)
bob.pendown()
bob.color("pink")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-120,120)
bob.pendown()
bob.color("orange")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(0,120)
bob.pendown()
bob.color("darkred")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(120,120)
bob.pendown()
bob.color("lime")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(60,180)
bob.pendown()
bob.color("indigo")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-60,180)
bob.pendown()
bob.color("deeppink")
bob.begin_fill()
bob.circle(50)
bob.end_fill()
#sss
bob.penup()
bob.goto(-180,180)
bob.pendown()
bob.color("tomato")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(180,180)
bob.pendown()
bob.color("cadetblue")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-180,-60)
bob.pendown()
bob.color("seagreen")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(180,-60)
bob.pendown()
bob.color("gold")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(120,240)
bob.pendown()
bob.color("rosybrown")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(120,-120)
bob.pendown()
bob.color("olivedrab")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(0,-120)
bob.pendown()
bob.color("plum")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-120,-120)
bob.pendown()
bob.color("paleturquoise")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(0,240)
bob.pendown()
bob.color("navy")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-120,240)
bob.pendown()
bob.color("darkorchid")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(180,-180)
bob.pendown()
bob.color("orangered")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-180,-180)
bob.color("fuchsia")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-60,-180)
bob.color("dimgray")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(60,-180)
bob.color("dodgerblue")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-60,300)
bob.color("turquoise")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(60,300)
bob.color("palevioletred")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-180,300)
bob.color("greenyellow")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(180,300)
bob.color("thistle")
bob.begin_fill()
bob.circle(50)
bob.end_fill()
#m
bob.penup()
bob.goto(300,300)
bob.color("cornflowerblue")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-300,300)
bob.color("teal")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(240,240)
bob.color("palegoldenrod")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-240,240)
bob.color("darkgrey")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(300,180)
bob.color("lavender")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-300,180)
bob.color("yellow")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-240,120)
bob.color("blue")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-300,60)
bob.color("purple")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-240,0)
bob.color("yellow")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-240,-120)
bob.color("red")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-300,-60)
bob.color("gray")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(240,0)
bob.color("yellow")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(240,120)
bob.color("orange")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-300,-180)
bob.color("tomato")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(300,60)
bob.color("darkblue")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(240,-120)
bob.color("blue")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(300,-60)
bob.color("red")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(300,-180)
bob.color("brown")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(360,120)
bob.color("plum")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(360,240)
bob.color("olivedrab")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(360,0)
bob.color("lightcoral")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(360,-120)
bob.color("lemonchiffon")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(420,60)
bob.color("tan")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(420,180)
bob.color("hotpink")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(420,300)
bob.color("slateblue")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(420,-60)
bob.color("cyan")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(420,-180)
bob.color("teal")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(420,-300)
bob.color("indigo")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(360,-240)
bob.color("mediumpurple")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(240,-240)
bob.color("sandybrown")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(120,-240)
bob.color("darkgreen")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(0,-240)
bob.color("turquoise")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-120,-240)
bob.color("peru")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-240,-240)
bob.color("peachpuff")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-300,-300)
bob.color("steelblue")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-180,-300)
bob.color("tomato")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(-60,-300)
bob.color("springgreen")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(60,-300)
bob.color("honeydew")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(180,-300)
bob.color("gold")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.penup()
bob.goto(300,-300)
bob.color("silver")
bob.begin_fill()
bob.circle(50)
bob.end_fill()

turtle.hideturtle
